<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <IsAotCompatible>true</IsAotCompatible>
        <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>

        <AssemblyName>PANiXiDA.Core.Infrastructure.Storage.S3</AssemblyName>

        <PackageId>PANiXiDA.Core.Infrastructure.Storage.S3</PackageId>
        <Description>S3-compatible file storage adapter for PANiXiDA.Core applications, providing uploads, downloads, deletion and presigned URLs.</Description>
        <PackageTags>dotnet;s3;amazon-s3;s3-compatible;file-storage;object-storage;infrastructure;presigned-urls</PackageTags>

        <RepositoryUrl>https://github.com/panixida-dotnet-core/infrastructure-storage-s3</RepositoryUrl>
        <PackageProjectUrl>https://github.com/panixida-dotnet-core/infrastructure-storage-s3</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
        <PackageReference Include="AWSSDK.S3" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="PANiXiDA.Core.Application" />
        <PackageReference Include="Nerdbank.GitVersioning">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PANiXiDA.Core.Infrastructure.Storage.S3.UnitTests" />
    </ItemGroup>
</Project>
